#!/usr/bin/env python3
"""Audit frozen FreshRetailNet calibration cells without fitting or selection.

Example:
  python code/analyze_natural_cells.py --package . \
    --output /tmp/natural_cells --table /tmp/fresh_cells_table.tex

The saved ``base`` is already management-group scaled. Consequently the
RC/base multiplier is cell_scale / category_scale, not cell_scale itself.
All mass shares below refer to recorded sales; none estimate missing demand.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def summarize(frame: pd.DataFrame, total_rows: int, total_mass: float) -> dict:
    n = len(frame)
    y = frame.sale_amount.to_numpy()
    b = frame.base.to_numpy()
    r = frame.risk_conditioned.to_numpy()
    mass = float(y.sum())
    eb = float(np.abs(b-y).sum())
    er = float(np.abs(r-y).sum())
    q = frame.predicted_stockout_risk.to_numpy()
    result = {
        "rows": int(n),
        "row_share_within_population": n / total_rows if total_rows else None,
        "recorded_sales_mass": mass,
        "recorded_sales_share_within_population": mass / total_mass if total_mass else None,
        "base_prediction_mass": float(b.sum()),
        "rc_prediction_mass": float(r.sum()),
        "base_absolute_error_mass": eb,
        "rc_absolute_error_mass": er,
        "error_reduction_base_minus_rc": eb-er,
        "wape_base": eb/mass if mass else None,
        "wape_rc": er/mass if mass else None,
        "wape_difference_rc_minus_base": (er-eb)/mass if mass else None,
        "population_wape_reduction_contribution": (eb-er)/total_mass if total_mass else None,
        "mean_q": float(q.mean()) if n else None,
        "stockout_row_fraction": float(frame.is_censored.mean()) if n else None,
    }
    for percentile in [0, 10, 25, 50, 75, 90, 100]:
        result[f"q_p{percentile:02d}"] = float(np.percentile(q, percentile)) if n else None
    return result


def write_table(path: Path, cells: pd.DataFrame, policy: dict) -> None:
    """Two readable tables: all 56 cells in the prespecified primary subset."""
    primary = cells[cells.population == "primary_no_recorded_stockout"]
    parts = []
    groups = sorted(int(c) for c in policy["category_scales"])
    for part, current in enumerate([groups[:4], groups[4:]], start=1):
        caption = (
            "FreshRetailNet primary-population cells (part " + str(part) + " of 2). "
            "The saved base is $\\hat s_c b$ and RC is $sb$; $s/\\hat s_c$ is the change relative to the reported base. "
            "Rows and sales percentages use the complete 8,020-row primary population as denominator, "
            "not each management group. $\\bar q$ is mean predicted stockout risk. "
            "The final columns are cell WAPE. Bin boundaries are pooled across management groups. "
            "Sales are recorded sales on rows with no annotated stockout; the table does not identify missing demand."
        )
        lines = [r"\begin{table}[p]", r"\caption{" + caption + "}",
                 rf"\label{{tab:fresh-cells-{part}}}",
                 r"\centering\small", r"\setlength{\tabcolsep}{4.1pt}",
                 r"\begin{tabular}{rrrrrrrrr}\toprule",
                 r"Bin & $s$ & $s/\hat s_c$ & Rows & Rows (\%) & Sales (\%) & $\bar q$ & Base & RC \\ \midrule"]
        for category in current:
            c = policy["category_scales"][str(category)]
            lines.append(rf"\multicolumn{{9}}{{l}}{{Management group {category}: base multiplier $\hat s_c={c:.6f}$}} \\")
            for _, row in primary[primary.management_group_id == category].sort_values("bin").iterrows():
                def val(key: str, digits: int = 5) -> str:
                    return "--" if pd.isna(row[key]) else f"{row[key]:.{digits}f}"
                lines.append(
                    f"{int(row['bin'])} & {row['cell_scale_s']:.4f} & {row['rc_to_reported_base_multiplier']:.4f} & "
                    f"{int(row['rows']):,} & {100*row['row_share_within_population']:.2f} & "
                    f"{100*row['recorded_sales_share_within_population']:.2f} & "
                    f"{val('mean_q',3)} & {val('wape_base')} & {val('wape_rc')} \\\\"
                )
            lines.append(r"\addlinespace[3pt]")
        lines.extend([r"\bottomrule\end{tabular}", r"\end{table}"])
        parts.append("\n".join(lines))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("% Generated by code/analyze_natural_cells.py; do not hand-edit.\n" + "\n\n".join(parts) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--table", type=Path)
    args = parser.parse_args()
    root = args.package.resolve()
    output = args.output.resolve()
    evidence = root / "evidence/freshretail/frozen_eval"
    sources = [evidence / "FINAL_POLICY.json", evidence / "EVAL_PREDICTIONS.csv.gz",
               evidence / "RESULTS.json", root / "code/freshretail/run_frozen_rc_eval.py",
               root / "code/freshretail/resume_frozen_rc_eval_after_engine_failure.py"]
    source_hashes = {str(p.relative_to(root)): sha256(p) for p in sources}
    policy = json.loads(sources[0].read_text())
    frame = pd.read_csv(sources[1])
    reference = json.loads(sources[2].read_text())
    checks = []

    def check(name: str, condition: bool) -> None:
        if not condition:
            raise AssertionError(name)
        checks.append(name)

    def close(name: str, actual: float, target: float) -> None:
        check(name, bool(np.isclose(actual, target, rtol=2e-12, atol=2e-10)))

    check("eight bins", policy["bins"] == 8)
    check("seven management groups", len(policy["category_scales"]) == 7)
    check("56 multiplier cells", len(policy["scales"]) == 56)
    check("embedded policy matches", policy == reference["final_policy"])
    check("finite saved predictions", bool(np.isfinite(frame.select_dtypes(include=np.number)).all().all()))
    check("nonnegative sales and predictions", bool((frame[["sale_amount", "base", "risk_conditioned"]] >= 0).all().all()))
    check("binary annotation", set(frame.is_censored.unique()) <= {0, 1})
    check("unique series-date", not frame.duplicated(["series_id", "dt"]).any())
    frame["bin"] = np.searchsorted(np.asarray(policy["edges"]), frame.predicted_stockout_risk, side="right") + 1
    frame["group_scale_c"] = [policy["category_scales"][str(c)] for c in frame.management_group_id]
    frame["cell_scale_s"] = [policy["scales"][f"{c}|{j-1}"] for c, j in zip(frame.management_group_id, frame.bin)]
    frame["rc_to_reported_base_multiplier"] = frame.cell_scale_s / frame.group_scale_c
    frame["raw_base_reconstructed"] = frame.base / frame.group_scale_c
    reconstructed_rc = frame.raw_base_reconstructed * frame.cell_scale_s
    max_error = float(np.abs(reconstructed_rc-frame.risk_conditioned).max())
    check("reported base requires group scale", bool((frame.group_scale_c != 1).all()))
    check("RC reconstructed from raw base and cell scale", bool(np.allclose(reconstructed_rc, frame.risk_conditioned, rtol=2e-13, atol=2e-13)))
    changes = frame.risk_conditioned - frame.base
    frame["direction_from_reported_base"] = np.select([changes > 1e-12, changes < -1e-12], ["uplift", "suppression"], default="unchanged")
    populations = {
        "all_recorded_sales": frame,
        "primary_no_recorded_stockout": frame[frame.is_censored == 0],
        "annotated_stockout_recorded_sales": frame[frame.is_censored == 1],
    }
    cells, directions, bins, summaries = [], [], [], {}
    for label, selected in populations.items():
        n, mass = len(selected), float(selected.sale_amount.sum())
        summary = summarize(selected, n, mass)
        summaries[label] = summary
        for category in sorted(int(c) for c in policy["category_scales"]):
            c = policy["category_scales"][str(category)]
            for j in range(1, 9):
                s = policy["scales"][f"{category}|{j-1}"]
                subset = selected[(selected.management_group_id == category) & (selected.bin == j)]
                cells.append({"population": label, "management_group_id": category, "bin": j,
                              "group_scale_c": c, "cell_scale_s": s, "rc_to_reported_base_multiplier": s/c,
                              "q_lower_bound": 0.0 if j == 1 else policy["edges"][j-2],
                              "q_upper_bound": 1.0 if j == 8 else policy["edges"][j-1],
                              **summarize(subset, n, mass)})
        for direction in ["uplift", "suppression", "unchanged"]:
            subset = selected[selected.direction_from_reported_base == direction]
            directions.append({"population": label, "direction_from_reported_base": direction, **summarize(subset, n, mass)})
        for j in range(1, 9):
            subset = selected[selected.bin == j]
            bins.append({"population": label, "bin": j, **summarize(subset, n, mass)})
        for key in ["rows", "recorded_sales_mass", "base_prediction_mass", "rc_prediction_mass", "base_absolute_error_mass", "rc_absolute_error_mass", "error_reduction_base_minus_rc"]:
            for name, records in [("cells", cells), ("directions", directions), ("bins", bins)]:
                close(f"{label}: {name} reconstruct {key}", sum(r[key] for r in records if r["population"] == label), summary[key])
        for name, records in [("cells", cells), ("directions", directions), ("bins", bins)]:
            for key in ["row_share_within_population", "recorded_sales_share_within_population"]:
                close(f"{label}: {name} {key} sum", sum(r[key] for r in records if r["population"] == label), 1.0)
    for label, original_key in [("all_recorded_sales", "secondary_all_recorded_sales"), ("primary_no_recorded_stockout", "primary_fully_available")]:
        summary = summaries[label]
        for method, column in [("base", "base"), ("risk_conditioned", "rc")]:
            close(f"{label} {method} frozen WAPE", summary[f"wape_{column}"], reference[original_key][method]["wape"])
            close(f"{label} {method} frozen mass", summary["recorded_sales_mass"], reference[original_key][method]["demand_mass"])
            close(f"{label} {method} frozen rows", summary["rows"], reference[original_key][method]["rows"])
    for row in cells:
        p = row["population"]
        g, j = row["management_group_id"], row["bin"]
        if row["recorded_sales_mass"]:
            close(f"{p} group {g} bin {j} contribution", row["recorded_sales_share_within_population"]*(row["wape_base"]-row["wape_rc"]), row["population_wape_reduction_contribution"])
    for group in reference["by_management_group"]:
        category = int(group["management_group_id"])
        selected_cells = [row for row in cells if row["population"] == "primary_no_recorded_stockout" and row["management_group_id"] == category]
        mass = sum(row["recorded_sales_mass"] for row in selected_cells)
        for method, column in [("base", "base"), ("risk_conditioned", "rc")]:
            close(f"group {category} {method} frozen WAPE", sum(row[f"{column}_absolute_error_mass"] for row in selected_cells)/mass, group[method]["wape"])
            close(f"group {category} {method} frozen mass", mass, group[method]["demand_mass"])
            close(f"group {category} {method} frozen rows", sum(row["rows"] for row in selected_cells), group[method]["rows"])
    for key in ["rows", "recorded_sales_mass", "base_absolute_error_mass", "rc_absolute_error_mass", "error_reduction_base_minus_rc"]:
        close(f"primary and stockout partition {key}", summaries["primary_no_recorded_stockout"][key]+summaries["annotated_stockout_recorded_sales"][key], summaries["all_recorded_sales"][key])
    for p in sources:
        check(f"input unchanged: {p.name}", sha256(p) == source_hashes[str(p.relative_to(root))])
    output.mkdir(parents=True, exist_ok=True)
    cell_df = pd.DataFrame(cells)
    cell_df.to_csv(output / "CELLS_ALL_POPULATIONS.csv", index=False, float_format="%.17g")
    pd.DataFrame(directions).to_csv(output / "DIRECTION_DECOMPOSITION.csv", index=False, float_format="%.17g")
    pd.DataFrame(bins).to_csv(output / "RISK_BIN_DISTRIBUTIONS.csv", index=False, float_format="%.17g")
    if args.table:
        write_table(args.table, cell_df, policy)
    report = {
        "status": "PASS", "check_count": len(checks), "checks": checks,
        "scope": "Post-hoc descriptive audit of saved frozen predictions; no new fit, policy selection, or raw evaluation access.",
        "fits": 0, "policy_searches": 0, "raw_eval_accesses": 0,
        "source_sha256": source_hashes, "analyzer_sha256": sha256(Path(__file__)),
        "baseline_definition": "saved base = raw nonnegative L1 prediction times management-group scale c; saved RC = raw prediction times cell scale s",
        "correct_change_multiplier": "s/c, not s",
        "max_rc_reconstruction_absolute_error": max_error,
        "bin_boundary_definition": "Seven pooled q quantiles over all eligible calibration rows, before management-group partitioning; searchsorted side=right; display bins 1..8.",
        "bin_edges": policy["edges"], "group_scales": policy["category_scales"],
        "denominator_definition": "Each population's row and recorded-sales totals, not each management group's totals.",
        "population_summaries": summaries,
        "direction_decomposition": directions,
        "bin_decomposition": bins,
        "interpretation": [
            "The primary population is outcome-conditioned on no annotated stockout. It is not the latent-demand population on stockout rows.",
            "Most primary rows are suppressed relative to the group-scaled base, but suppressed rows increase aggregate absolute-error mass. Uplifted rows provide the aggregate reduction.",
            "High predicted risk remains present in the primary population; absence of realized annotated stockout does not imply low ex ante risk.",
            "Direction is descriptive and relative to the reported baseline. This audit neither identifies causal effects nor establishes the same latent-demand mechanism as mechanical M5 censoring.",
        ],
    }
    (output / "NATURAL_CELL_AUDIT.json").write_text(json.dumps(report, indent=2, sort_keys=True, allow_nan=False)+"\n")
    print(json.dumps({"status": "PASS", "checks": len(checks), "max_rc_error": max_error, "output": str(output)}, indent=2))


if __name__ == "__main__":
    main()
