"""Resume only evaluation after a missing parquet dependency; zero refits."""
from run_forward_controls import *
out=ROOT/'evidence/forward_controls/fresh';ev=ROOT/'evidence/freshretail/frozen_eval';frozen=json.loads((out/'fresh_FROZEN_POLICIES.json').read_text());p=frozen['policies'];best=frozen['selected_stack']
dump(out/'RESUME_PROTOCOL.json',{'created_utc':now(),'reason':'pyarrow missing after policy and final stack saved; resume without any model fit or selection','new_fits':0,'new_selections':0,'policy_sha256':sha(out/'fresh_FROZEN_POLICIES.json'),'stack_sha256':sha(out/'fresh_FINAL_STACK.txt'),'script_sha256':sha(__file__)})
t=pd.read_pickle(ROOT/'inputs/freshretail/freshretail_2000_train_only.pkl.gz');t.attrs={};t=normalize_frame(t);t['_source_split']='train';dates=infer_split_dates(t);rows,num,cat=make_supervised(t,horizons=range(1,8),max_train_rows=600000,seed=20260907,development_holdout_days=35);fit=split_supervised(rows,dates)['fit'];enc=SmoothedTargetEncoder(categorical=cat,numeric=num,smoothing=30);enc.fit(fit,fit.sale_amount.to_numpy(float),uncensored=fit.is_censored.eq(0).to_numpy());del rows,fit;gc.collect()
dump(out/'FEATURE_SCHEMA.json',{'features':enc.feature_names_+['category_scaled_base','q'],'note':'Frozen policy lists raw source columns; this file expands each encoded categorical column into target-encoding and frequency coordinates.'})
e=normalize_frame(pd.read_parquet(ROOT/'inputs/freshretail/official_eval.parquet'));e['_source_split']='eval';e=e[e.series_id.astype(str).isin(set(t.series_id.astype(str)))];c=pd.concat([t,e],ignore_index=True);r,_,_=make_supervised(c,horizons=range(1,8),max_train_rows=7,seed=20260907,development_holdout_days=35);test=split_supervised(r,infer_split_dates(c))['test'].reset_index(drop=True);tx=enc.transform(test)
base=xgb.Booster();base.load_model(ev/'base_l1.ubj');base.set_param({'nthread':4});risk=xgb.Booster();risk.load_model(ev/'stockout_risk.ubj');risk.set_param({'nthread':4});dm=xgb.DMatrix(tx);raw=np.maximum(base.predict(dm)-1,0);q=np.clip(risk.predict(dm),0,1)
td=pd.DataFrame({'series':test.series_id.astype(str),'day':test.dt.astype(str),'group':test.management_group_id.astype(str),'y':test.sale_amount.to_numpy(float),'raw':raw,'q':q,'available':test.is_censored.eq(0),'store':test.store_id.astype(str),'product':test.product_id.astype(str)})
pred=apply_controls(td,p);model=lgb.Booster(model_file=str(out/'fresh_FINAL_STACK.txt'));pred['stack']=np.maximum(pred['base']+model.predict(np.column_stack([tx,pred['base'],td.q]).astype(np.float32),num_threads=4),0)
saved=pd.read_csv(ev/'EVAL_PREDICTIONS.csv.gz');assert np.array_equal(td.series.to_numpy(),saved.series_id.astype(str).to_numpy());assert np.max(abs(pred['rc']-saved.risk_conditioned.to_numpy()))<2e-12
for k,f in pred.items():td[k]=f
td.to_csv(out/'fresh_EVAL_PREDICTIONS.csv.gz',index=False);np.savez_compressed(out/'fresh_EVAL_FEATURES.npz',x=tx)
result=report(td,pred,['series','store','product','day']);result['risk_metrics']={'auc':float(roc_auc_score(~td.available,td.q)),'brier':float(brier_score_loss(~td.available,td.q)),'event_rate':float((~td.available).mean()),'constant_brier':float((~td.available).mean()*td.available.mean()),'eligible_auc':'undefined: all eligible outcomes have H=0'};result['selected_stack']=best;result['top_scale']=p['top_scale'];result['fallback_cells']=sum(v['fallback'] for v in p['support']);dump(out/'fresh_RESULTS.json',result);dump(out/'COMPLETE.json',{'finished_utc':now(),'files':{v.name:sha(v) for v in out.iterdir() if v.is_file() and v.name!='COMPLETE.json'}});print('FRN COMPLETE',result['eligible']['metrics'],flush=True)
